# 1일차 분석

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
from tslearn.metrics import dtw
from tslearn.clustering import TimeSeriesKMeans
from tslearn.utils import to_time_series_dataset

fNirs_list=[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
score_list=[]
for i in range(1,7):
    temp=[]
    raw_fNirs=pd.read_csv("D:/Dataset/f_Nirs datasets/raw_data/Task C/C_K-"+str(i)+"_raw.csv")
    for j in range(0,15):
        fNirs_list[j].append(raw_fNirs.iloc[:,j])


In [4]:
from tslearn.clustering import silhouette_score
total_label=[[],[],[],[],[],[]]
for i in range(0,15):
    X=to_time_series_dataset(fNirs_list[i])
    model = TimeSeriesKMeans(n_clusters=2, metric="dtw",
                            max_iter=10, random_state=0)
    model.fit(X)
    label=model.predict(X)
    total_label[0].append(label[0])
    total_label[1].append(label[1])
    total_label[2].append(label[2])
    total_label[3].append(label[3])
    total_label[4].append(label[4])
    total_label[5].append(label[5])
    print(silhouette_score(X,label,metric='dtw'))

0.8243641523160173
0.5550915530700484
0.5936293104717163
0.5231563456191423
0.6464388064721401
0.3910295683085909
0.5345625580406289
0.6364478074010382
0.6938163916124384
0.4426575212960775
0.6068595174163488
0.8446261234114889
0.3768862361474125
0.8953733904408819
0.4570048363591328


In [5]:
total_label

[[1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1],
 [0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1],
 [0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 1],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1]]

In [16]:
from kmodes.kmodes import KModes
import numpy as np
kmodes=KModes(n_clusters=3)
total_label=np.array(total_label)
kmodes.fit_predict(total_label)

array([0, 0, 1, 1, 2, 0], dtype=uint16)

In [18]:
self_report=pd.read_csv("D:/Dataset/f_Nirs datasets/k1~12_self-report_dataset.csv")
day1=self_report[0:6]
day1.drop(['subjectkey','date','age','sex','right_handed','piano_year','piano_major','impro_experience','condition','post_C_IF_10','pre_SE_10','pre_SE_11',
           'post_A_IF_10','post_A_diff','post_B_diff','post_A_SE_10','post_A_SE_11','post_B_SE_10','post_B_SE_11'],axis=1,inplace=True)
for i in range(1,10):
    day1.drop(['pre_SE_0'+str(i)],axis=1,inplace=True)
    day1.drop(['post_B_IF_0'+str(i)],axis=1,inplace=True)
    day1.drop(['post_A_IF_0'+str(i)],axis=1,inplace=True)
    day1.drop(['post_A_SE_0'+str(i)],axis=1,inplace=True)
    day1.drop(['post_B_SE_0'+str(i)],axis=1,inplace=True)
day1

C:\Users\bml05\AppData\Local\Temp\ipykernel_11288\1677721423.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day1.drop(['subjectkey','date','age','sex','right_handed','piano_year','piano_major','impro_experience','condition','post_C_IF_10','pre_SE_10','pre_SE_11',
C:\Users\bml05\AppData\Local\Temp\ipykernel_11288\1677721423.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day1.drop(['pre_SE_0'+str(i)],axis=1,inplace=True)
C:\Users\bml05\AppData\Local\Temp\ipykernel_11288\1677721423.py:7: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentati

post_C_SE_01  post_C_SE_02  post_C_SE_03  post_C_SE_04  post_C_SE_05  \
0             4             4             4             5             3   
1             5             4             4             5             3   
2             4             5             5             5             4   
3             4             5             4             5             3   
4             4             5             5             5             3   
5             4             4             4             5             3   

   post_C_SE_06  post_C_SE_07  post_C_SE_08  post_C_SE_09  post_C_SE_10  ...  \
0             3             3             5             5             4  ...   
1             4             3             5             5             4  ...   
2             4             4             5             5             5  ...   
3             4             3             4             5             5  ...   
4             4             3             4             5             5  ...   
5             3             3             4             4             5  ...   

   post_C_IF_01  post_C_IF_02  post_C_IF_03  post_C_IF_04  post_C_IF_05  \
0             5             4             4             4             4   
1             4             5             5             4             5   
2             5             5             5             5             5   
3             5             5             5             4             5   
4             4             5             5             4             4   
5             4             4             4             4             4   

   post_C_IF_06  post_C_IF_07  post_C_IF_08  post_C_IF_09  post_C_diff  
0             4             4             4             5            4  
1             4             4             4             5            3  
2             5             5             5             5            3  
3             5             5             5             5            3  
4             5             5             5             5            3  
5             4             5             5             2            4  

[6 rows x 22 columns]

In [19]:
from sklearn.metrics import silhouette_score
from kmodes.kprototypes import KPrototypes
kmodes=KPrototypes(n_clusters=3)
kmodes.fit_predict(day1)
print(silhouette_score(day1,kmodes.labels_))

NotImplementedError: No categorical data selected, effectively doing k-means. Present a list of categorical columns, or use scikit-learn's KMeans instead.

In [57]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
kmeans=KMeans(n_clusters=3,random_state=0)
clusters=kmeans.fit(day1_pcaDf)
print(silhouette_score(day1_pcaDf,clusters.labels_))
clusters.labels_

0.4009257247312387


array([2, 0, 0, 0, 0, 1])

# 2일차 분석

In [9]:
fNirs_list=[[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]]
score_list=[]
for i in range(7,13):
    temp=[]
    raw_fNirs=pd.read_csv("D:/Dataset/f_Nirs datasets/raw_data/Task C/C_K-"+str(i)+"_raw.csv")
    for j in range(0,15):
        fNirs_list[j].append(raw_fNirs.iloc[:,j])

In [18]:
from tslearn.clustering import silhouette_score
total_label=[[],[],[],[],[],[]]
for i in range(0,15):
    X=to_time_series_dataset(fNirs_list[i])
    model = TimeSeriesKMeans(n_clusters=2, metric="dtw",
                            max_iter=10, random_state=0)
    model.fit(X)
    label=model.predict(X)
    total_label[0].append(label[0])
    total_label[1].append(label[1])
    total_label[2].append(label[2])
    total_label[3].append(label[3])
    total_label[4].append(label[4])
    total_label[5].append(label[5])
    print(silhouette_score(X,label,metric='dtw'))

0.6919178555995833
0.6270721589050755
0.6905112379938396
0.07931544017438032
0.7663687556281037
0.7838510989010022
0.6601610516812864
0.7872236367485664
0.6470508143146534
0.7322092178139002
0.3925670062462517
0.51192037350136
0.383774894061725
0.6249052825182541
0.5317224899077636


In [19]:
total_label


[[0, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0],
 [0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0],
 [0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
 [0, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0],
 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
 [1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1]]

In [36]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
label_pca = pca.fit_transform(total_label)
label_pcaDf = pd.DataFrame(data=label_pca, columns = ['principal component1', 'principal component2'])
label_pcaDf

principal component1  principal component2
0              0.385878             -0.730549
1              1.740993             -0.649978
2             -0.267669             -0.066142
3             -1.445623             -0.398881
4             -0.942231              0.106385
5              0.528652              1.739165

In [37]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
kmeans=KMeans(n_clusters=3,random_state=0)
clusters=kmeans.fit(label_pcaDf)
print(silhouette_score(label_pcaDf,clusters.labels_))
clusters.labels_

0.36972182898874645


array([1, 1, 0, 0, 0, 2])

In [38]:
day2=self_report[6:12]
day2.drop(['subjectkey','date','age','sex','right_handed','piano_year','piano_major','impro_experience','condition','post_C_IF_10','pre_SE_10','pre_SE_11',
           'post_A_IF_10','post_A_diff','post_B_diff','post_A_SE_10','post_A_SE_11','post_B_SE_10','post_B_SE_11'],axis=1,inplace=True)
for i in range(1,10):
    day2.drop(['pre_SE_0'+str(i)],axis=1,inplace=True)
    day2.drop(['post_B_IF_0'+str(i)],axis=1,inplace=True)
    day2.drop(['post_A_IF_0'+str(i)],axis=1,inplace=True)
    day2.drop(['post_A_SE_0'+str(i)],axis=1,inplace=True)
    day2.drop(['post_B_SE_0'+str(i)],axis=1,inplace=True)
day2

C:\Users\bml05\AppData\Local\Temp\ipykernel_20632\3342431656.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day2.drop(['subjectkey','date','age','sex','right_handed','piano_year','piano_major','impro_experience','condition','post_C_IF_10','pre_SE_10','pre_SE_11',
C:\Users\bml05\AppData\Local\Temp\ipykernel_20632\3342431656.py:5: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  day2.drop(['pre_SE_0'+str(i)],axis=1,inplace=True)
C:\Users\bml05\AppData\Local\Temp\ipykernel_20632\3342431656.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentati

post_C_SE_01  post_C_SE_02  post_C_SE_03  post_C_SE_04  post_C_SE_05  \
6              2             4             5             5             3   
7              5             5             5             5             4   
8              4             4             4             5             4   
9              4             4             4             5             4   
10             3             4             5             5             4   
11             5             5             5             5             5   

    post_C_SE_06  post_C_SE_07  post_C_SE_08  post_C_SE_09  post_C_SE_10  ...  \
6              3             3             3             3             4  ...   
7              4             4             5             4             4  ...   
8              4             1             5             5             3  ...   
9              5             4             5             5             5  ...   
10             2             2             5             4             5  ...   
11             4             5             5             1             5  ...   

    post_C_IF_01  post_C_IF_02  post_C_IF_03  post_C_IF_04  post_C_IF_05  \
6              5             3             4             4             4   
7              4             4             4             4             4   
8              5             5             5             5             4   
9              5             2             4             5             5   
10             5             4             5             4             4   
11             5             5             5             5             5   

    post_C_IF_06  post_C_IF_07  post_C_IF_08  post_C_IF_09  post_C_diff  
6              5             5             5             3            3  
7              4             4             4             3            2  
8              5             5             5             1            3  
9              5             5             5             2            5  
10             4             5             5             2            4  
11             4             5             5             1            2  

[6 rows x 22 columns]

In [39]:
from sklearn.decomposition import PCA
pca = PCA(n_components=2)
day2_pca = pca.fit_transform(day2)
day2_pcaDf = pd.DataFrame(data=day2_pca, columns = ['principal component1', 'principal component2'])
day2_pcaDf

principal component1  principal component2
0             -1.225259             -0.600834
1              1.405402              0.718356
2             -1.363142             -1.036228
3             -1.081917              3.569367
4             -2.381971             -1.852477
5              4.646887             -0.798183

In [40]:
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
kmeans=KMeans(n_clusters=3,random_state=0)
clusters=kmeans.fit(day2_pcaDf)
print(silhouette_score(day2_pcaDf,clusters.labels_))
clusters.labels_

0.45346756112927467


array([0, 1, 0, 2, 0, 1])